Project_2_cmpg323/Models/DeleteImageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_2_cmpg323.Models
{
    public class DeleteImageModel
    {
        public int Id { get; set; }
    }
}

Project_2_cmpg323/Models/ErrorViewModel.cs
using System;

namespace Project_2_cmpg323.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project_2_cmpg323/Models/GalleryDetailModel.cs
using System;
using System.Collections.Generic;

namespace Project_2_cmpg323.Models
{
    public class GalleryDetailModel
    {
        public int Id { get; set; }
        public string  Title { get; set; }
        public DateTime CreatedOn { get; set; }
        public string Url { get; set; }

        public List<string> Tags { get; set; }
    }
}

Project_2_cmpg323/Models/GalleryIndexModel.cs
using SimpleImageGallery.Data.Models;
using System.Collections.Generic;

namespace Project_2_cmpg323.Models
{
    public class GalleryIndexModel
    {
        public IEnumerable<GalleryImage> Images { get; set; }
        public string SearchQuery { get; set; }
    }
}

Project_2_cmpg323/Models/UpdateImageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Project_2_cmpg323.Models
{
    public class UpdateImageModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Tags { get; set; }
    }
}

Project_2_cmpg323/Models/UploadImageModel.cs
using Microsoft.AspNetCore.Http;

namespace Project_2_cmpg323.Models
{
    public class UploadImageModel
    {
        public string Title { get; set; }
        public string Tags { get; set; }
        public IFormFile ImageUpload { get; set; }
    }
}

Project_2_cmpg323/Controllers/GalleryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Project_2_cmpg323.Models;
using SimpleImageGallery.Data;
using System.Linq;
using System.Security.Claims;

namespace Project_2_cmpg323.Controllers
{
    [Authorize]
    public class GalleryController : Controller
    {
        private readonly IImage _imageService;

        public GalleryController(IImage imageService) {
            _imageService = imageService;
        }

        public IActionResult Index()
        {
            string strCurrentUserID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var imageList = _imageService.GetWithUserId(strCurrentUserID);
            var model = new GalleryIndexModel()
            {
                Images = imageList,
                SearchQuery = ""
            };

            return View(model);
        }

        public IActionResult Detail(int id)
        {
            var image = _imageService.GetById(id);

            var model = new GalleryDetailModel()
            {
                Id = image.Id,
                Title = image.Title,
                CreatedOn = image.Created,
                Url = image.Url,
                Tags = image.Tags.Select(t => t.Description).ToList()
            };

            return View(model);
        }
    }
}

Project_2_cmpg323/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Project_2_cmpg323.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Project_2_cmpg323.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

Project_2_cmpg323/Controllers/ImageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Project_2_cmpg323.Models;
using SimpleImageGallery.Data;
using SimpleImageGallery.Services;
using System;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Project_2_cmpg323.Controllers
{
    [Authorize]
    public class ImageController : Controller
    {
        private IConfiguration _config;
        private IImage _imageService;
        private string AzureConnectionString { get; }

        public ImageController(IConfiguration config, IImage imageService)
        {
            _config = config;
            _imageService = imageService;
            AzureConnectionString = _config["AzureStorageConnectionString"];
        }

        public IActionResult Upload()
        {
            var model = new UploadImageModel();
            return View(model);
        }

        public IActionResult Update()
        {
            var model = new UpdateImageModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateOldImage(int Id, string Title, string Tags)
        {
            try
            {
                await _imageService.UpdateImage(Id, Title, Tags);
                return RedirectToAction("index", "Gallery");
            }
            catch(Exception)
            {
                return RedirectToAction("index", "Gallery");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int Id)
        {
            try
            {
                await _imageService.DeleteImage(Id);
                return RedirectToAction("index", "Gallery");
            }
            catch(Exception)
            {
                return RedirectToAction("index", "Gallery");
            }
            
        }

        [HttpPost]
        public async Task<IActionResult> UploadNewImage(IFormFile file, string tags, string title)
        {
            try
            {
                var container = _imageService.GetBlobContainer(AzureConnectionString, "images");

                var content = ContentDispositionHeaderValue.Parse(file.ContentDisposition);
                var fileName = content.FileName.Trim('"');

                //Get current user
                string strCurrentUserID = User.FindFirstValue(ClaimTypes.NameIdentifier);

                //Get a reference to a Block Blob
                var blockBlob = container.GetBlockBlobReference(fileName);

                await blockBlob.UploadFromStreamAsync(file.OpenReadStream());
                await _imageService.SetImage(title, tags, blockBlob.Uri, strCurrentUserID);

                return RedirectToAction("Index", "Gallery");
            }
            catch(Exception)
            {
                return RedirectToAction("Index", "Gallery");
            }

        }


    }
}

Project_2_cmpg323/Views/Gallery/Detail.cshtml
@model Project_2_cmpg323.Models.GalleryDetailModel

<div class="gallery-image-container body-content">
    <div class="row image-detail-container">
        <div class="image-detail">
            <img src="@Model.Url" alt="@Model.Title" />
        </div>
    </div>
    <div class="row image-detail-meta">
        <span>Title: @Model.Title</span>
        <span>Uploaded: @Model.CreatedOn</span>
    </div>
    <div class="row controls">
        <!--Back to gallery button-->
        <a class="btn btn-primary" asp-controller="Gallery" asp-action="Index">Back to Gallery</a>

        <!--Update image button-->
        <a class="btn btn-primary" asp-controller="Image" asp-action="Update" asp-route-id="@Model.Id">Update/Delete</a>

        <!--Download image button-->
        <a class="btn btn-primary " href="@Model.Url">Download</a>

    </div>
</div>

Project_2_cmpg323/Views/Gallery/Index.cshtml
@model Project_2_cmpg323.Models.GalleryIndexModel

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
        body {
            background-image: url('@Url.Content("~/images/aspbackgroundimage.png")');
            background-repeat: no-repeat, repeat;
            background-size: cover;
        }
        h1{
            text-align: center;
        }
</style>

<div class="container body=content">

    <h1><b>Gallery Items</b></h1>

    <div class="row gallery-content">
        @foreach (var image in Model.Images)
        {
            <div class="gallery-image-container drop-shadow">
                <a asp-controller="Gallery" asp-action="Detail" asp-route-id="@image.Id">
                    <div class="gallery-image" style="background-image:url(@image.Url)"></div>
                </a>
            </div>
        }
    </div>
</div>

Project_2_cmpg323/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
        body {
            background-image: url('@Url.Content("~/images/aspbackgroundimage.png")');
            background-repeat: no-repeat, repeat;
            background-size: cover;
        }
</style>

<h2>@ViewData["Title"]</h2>
<h3>Easy to use gallery page</h3>

<p>
    For this project we have been given the task to develop a web application that serves as an online platform allowing
    users to store, view and share photos. Users must register before they can utilise the platform. When the user has
    successfully registered, they will be able to view their own photos and view the photos that have been shared with
    them. Users that have registered and logged into the platform must be able to create and update the metadata of each
    photo they have access to. Users should be able to share their photos with other users that have also registered to
    the platform. Users must be able to download the photos they have access to. The web application should be consistent
    and easy-to-use for all clients.
</p>

Project_2_cmpg323/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
        body {
            background-image: url('@Url.Content("~/images/aspbackgroundimage.png")');
            background-repeat: no-repeat, repeat;
            background-size: cover;
        }
</style>

<h2>@ViewData["Title"]</h2>
<h3>My Student details</h3>

<address>
    <strong>Name:</strong> Sven <br />
    <strong>Surname:</strong> Beyleveld <br />
    <strong>Student Number:</strong> 28428706 <br />
    <strong>Phone Number:</strong> 065 922 4495 <br />

</address>

<address>
    <strong>Email:</strong> svenbeyleveld1998@gmail.com
</address>

Project_2_cmpg323/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            background-image: url('@Url.Content("~/images/aspbackgroundimage.png")');
            background-repeat: no-repeat, repeat;
            background-size: cover;
        }
        h1 {
            text-align: center;
            padding-top:30%;
        }

        h2 {
            text-align: center;
        }
    </style>
</head>
<body>
    <h1><b>WELCOME TO EVERGALLERY</b></h1>
    <p><h2>HOME</h2></p>
</body>
</html>

Project_2_cmpg323/Views/Image/Update.cshtml
@model Project_2_cmpg323.Models.UpdateImageModel


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            background-image: url('@Url.Content("~/images/aspbackgroundimage.png")');
            background-repeat: no-repeat, repeat;
            background-size: cover;
        }
    </style>

<div class="container body-content">
    <div class="row upload-container">
        <div class="upload-form drop-shadow">
            <form asp-action="UpdateOldImage"
                  id="upload-form">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <h1>Update Image:</h1>
                    <h3>Edit Image Data:</h3>
                
                <div class="form-group">
                    <label asp-for="Id"></label>
                    <input asp-for="Id" class="form-control" value="@ViewContext.RouteData.Values["Id"]" readonly/>
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" value="Enter new Title Here.." OnClick="this.value=''"/>
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Tags"></label>
                    <input asp-for="Tags" class="form-control" value="Enter new Tag Here.." OnClick="this.value=''"/>
                    <span asp-validation-for="Tags" class="text-danger"></span>
                </div>
                <div class="submit">
                    <button type="submit" id="btn-upload" class="btn btn-info" value="Update">
                        Update
                    </button>
                </div>               

            </form>

            <form asp-action="Delete"
                  id="upload-form">
                
                <h3>Delete Image Data:</h3> 
                
                <div class="form-group">
                    <label asp-for="Id"></label>
                    <input asp-for="Id" class="form-control" value="@ViewContext.RouteData.Values["Id"]" readonly/>
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <!--Delete image button-->
                <div class="submit">
                    <button type="submit" id="btn-upload" class="btn btn-info" value="Delete">
                        Delete
                    </button>
                </div>

            </form>

        </div>
    </div>
</div>

Project_2_cmpg323/Views/Image/Upload.cshtml
@model Project_2_cmpg323.Models.UploadImageModel

<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
        body {
            background-image: url('@Url.Content("~/images/aspbackgroundimage.png")');
            background-repeat: no-repeat, repeat;
            background-size: cover;
        }
</style>

<div class="container body-content">
    <div class="row upload-container">
        <div class="upload-form drop-shadow">
            <form asp-action="UploadNewImage"
                  method="post"
                  enctype="multipart/form-data"
                  id="upload-form">

                <h1>Upload Image:</h1>
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" value="Enter new Title Here.." OnClick="this.value=''"/>
                </div>
                <div class="form-group">
                    <label asp-for="Tags"></label>
                    <input asp-for="Tags" class="form-control" value="Enter new Title Here.." OnClick="this.value=''"/>
                </div>
                <div>
                    <label class="btn btn-default btn-file">
                        Browse for Image
                        <input type="file" name="file" style="display: none" />
                    </label>
                </div>
                <div class="submit">
                    <button type="submit" id="btn-upload" class="btn btn-info">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

Project_2_cmpg323/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_2_cmpg323</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Home</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Gallery" asp-action="Index">Gallery</a></li>
                    <li><a asp-controller="Image" asp-action="Upload">Upload</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - Project_2_cmpg323</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>